Feature/simplesaml
scuolaonlineservice/sos-users pull request #1
Opened 2019-09-01 17:51 UTC by P2-718na

Modulo per usare Google SP con Joomla IDP.

2019-09-23 14:20 UTC, nicofuccella requested changes
Sistema le cose commentate e anche la history di git (nessun commit "mods"...).

2019-09-23 14:20 UTC, nicofuccella commented on Dockerfile
> +
Manca `apt-get install -y`. Senza quello il container non riesce a buildare. Sicuro di averlo provato?

2019-09-23 14:20 UTC, nicofuccella commented on Dockerfile
> +COPY saml /etc/nginx/sites-available/saml
Usa il conf.d piuttosto che sites-available

2019-09-23 14:20 UTC, nicofuccella commented on README.md
> +  5. È possibile testare il componente `JoomlaAuth` accedendo al pannello admin
Non mi hai detto che in questo pannello di simplesaml mi devo anche loggare

2019-09-23 14:20 UTC, nicofuccella commented on docker-compose.yml
> +  web:
aggiungi container_name

2019-09-23 14:20 UTC, nicofuccella commented on joomla/components/com_samllogin/admin/index.html
> +403
Perchè 403?

2019-09-23 14:20 UTC, nicofuccella commented on joomla/components/com_samllogin/admin/samllogin.xml
> +	<author>Robbie Jackson</author>
Sistema i dati di autore, ecc...

2019-09-23 14:20 UTC, nicofuccella commented on joomla/components/com_samllogin/admin/sql/index.html
> +403
Perchè 403?

2019-09-23 14:20 UTC, nicofuccella commented on README.md
> +    Modificare i campi `redirect_url` e `verify_url` nel file `config/authsources.php`.
simplesamlphp/config/authsources.php

2019-09-23 14:20 UTC, nicofuccella commented on joomla/components/com_samllogin/admin/samllogin.xml
> +		<menu link='index.php?option=com_samllogin'>Hello World!</menu>
Perchè hello world?

2019-09-23 14:20 UTC, nicofuccella commented on simplesamlphp/config/authsources.php
> +    'redirect_url' => 'http://DOMAIN_NAME/index.php?option=com_samllogin',
Se questo file deve essere modificato con valori custom, perchè non hai un file .template o .sample commitatto, e non ignori questo?

2019-09-23 14:20 UTC, nicofuccella commented on simplesamlphp/config/authsources.php
> +<?php
Aggiungi dei commenti a questo file

2019-09-23 14:20 UTC, nicofuccella commented on simplesamlphp/metadata/saml20-idp-hosted.php
> +<?php
Commenta questo file, che sennò non si capisce il suo ruolo

2019-09-23 14:20 UTC, nicofuccella commented on joomla/components/com_samllogin/site/controller.php
> +    if ($db->getAffectedRows($result) === 0) {
$result non serve come argomento di getAffectedRows

2019-09-23 14:20 UTC, nicofuccella commented on joomla/components/com_samllogin/site/views/samllogin/view.html.php
> +    $redirect_uri = $app->input->get('redirect_uri', false, 'STRING');
Perchè questo redirect? Cosa c'è di sbagliato con l'andare avanti nella view?

2019-09-23 14:20 UTC, nicofuccella commented on joomla/components/com_samllogin/site/views/samllogin/view.html.php
> +    if($id == 0)  {
Valuta di fare un redirect con
```
$app->redirect(
        "/index.php?option=com_users&view=login"
      );
```

2019-09-23 14:20 UTC, nicofuccella commented on joomla/components/com_samllogin/site/controller.php
> +class SAMLLoginController extends JControllerLegacy {
Estendi da `\Joomla\CMS\MVC\Controller\BaseController`. Non usiamo cose deprecate!!!

2019-09-23 14:20 UTC, nicofuccella commented on joomla/components/com_samllogin/site/views/samllogin/view.html.php
> +class SAMLLoginViewSAMLLogin extends JViewLegacy {
Estendi \Joomla\CMS\MVC\View\HtmlView. Non usiamo cose deprecate!!!

2019-09-23 14:20 UTC, nicofuccella commented on joomla/components/com_samllogin/site/controller.php
> +      ->where($db->quoteName('token').' = '.$token)
Invece di generarti un token random, perchè non usare la session? 
`JFactory::getSession()->getId()`
Puoi anche avere l'expiration
`JFactory::getSession()->getExpire()`

2019-09-23 14:20 UTC, nicofuccella commented on joomla/components/com_samllogin/site/views/samllogin/view.html.php
> +    if($id == 0)  {
Questa parte l'ho aggiornata io con i redirect per migliorare l'esperienza utente. Guarda il mio branch omonimo di questo

2019-09-23 14:20 UTC, nicofuccella commented on simplesamlphp/metadata/saml20-sp-remote.php
> +<?php
Un commento qui ci vorrebbe...

2019-09-23 14:20 UTC, nicofuccella commented on simplesamlphp/modules/joomlamodule/lib/Auth/Source/JoomlaAuth.php
> +<?php
Aggiungi dei commenti per spiegare bene questo file...

2019-09-23 14:20 UTC, nicofuccella commented on simplesamlphp/modules/joomlamodule/www/linkback.php
> +<?php
Commenti, che sennò non si capisce cosa faccia questo...

2019-09-24 12:53 UTC, P2-718na commented on Dockerfile
> +COPY saml /etc/nginx/sites-available/saml
Il container sample-scuola usa sites-available, vuoi che usi lo stesso conf.d?

2019-09-24 12:59 UTC, P2-718na commented on joomla/components/com_samllogin/admin/index.html
> +403
Tutti i file index.html nei moduli servono per evitare che venga fatto il listing della cartella. Ho messo 403 così come risposta da unauthorized

2019-09-24 13:40 UTC, P2-718na commented on joomla/components/com_samllogin/site/controller.php
> +      ->where($db->quoteName('token').' = '.$token)
Ho usato una stringa casuale al posto dell'id in modo da evitare che qualcuno possa fingersi un'altro utente rubando la sua ID. Forse è inutile, ma lo lascerei così per sicurezza (non so se le ID sono guessabili o altro, non ho trovato documentazione che spieghi come Joomla! gestisca le sessioni).

2019-09-24 15:22 UTC, P2-718na commented on joomla/components/com_samllogin/admin/sql/index.html
> +403
vedi altra risposta

2019-09-24 15:25 UTC, P2-718na commented on joomla/components/com_samllogin/site/views/samllogin/view.html.php
> +    $redirect_uri = $app->input->get('redirect_uri', false, 'STRING');
Se redirect_uri non è specificato, vuol dire che un utente è arrivato alla view senza passare per simplesaml. Viene mostrato un errore, visto che questa view si occupa solo del login con simplesaml

2019-09-24 15:27 UTC, P2-718na commented
Ho sistemato le cose nei commenti. Guarda le risposte che ti ho dato e dimmi se va bene tutto.

2019-10-01 07:37 UTC, nicofuccella commented on Dockerfile
> +COPY saml /etc/nginx/sites-available/saml
si

2019-10-01 07:39 UTC, nicofuccella commented on joomla/components/com_samllogin/admin/index.html
> +403
si, ma la convenzione con joomla è pagina bianca
```html
<html><body bgcolor="#FFFFFF"></body></html>
```

2019-10-01 07:41 UTC, nicofuccella commented on joomla/components/com_samllogin/site/controller.php
> +      ->where($db->quoteName('token').' = '.$token)
Gli id delle sessioni dubito proprio che siano guessabili. Non aggiungiamo codice inutile

2019-10-01 07:55 UTC, nicofuccella requested changes
Sistema il discorso token e implementa le modifiche del file che ti ho linkato e siamo perfetti.
Ben fatto!

2019-10-01 07:55 UTC, nicofuccella commented on joomla/components/com_samllogin/site/views/samllogin/view.html.php
> +    $redirect_uri = $app->input->get('redirect_uri', false, 'STRING');
Togli il token random e guarda https://github.com/nicofuccella/sos-users/blob/feature/simplesaml/joomla/components/com_samllogin/site/views/samllogin/view.html.php. Migliore user experience

2019-10-04 15:09 UTC, P2-718na commented on Dockerfile
> +COPY saml /etc/nginx/sites-available/saml
Risolto: https://github.com/scuolaonlineservice/sos-users/blob/76346a3c4adb830535f1d045fa50b529fb9f2c4e/Dockerfile#L14

2019-10-04 15:09 UTC, P2-718na commented on joomla/components/com_samllogin/admin/index.html
> +403
Risolto per tutti gli index.html

2019-10-04 15:12 UTC, P2-718na commented on joomla/components/com_samllogin/site/views/samllogin/view.html.php
> +    $redirect_uri = $app->input->get('redirect_uri', false, 'STRING');
Risolto: https://github.com/scuolaonlineservice/sos-users/blob/76346a3c4adb830535f1d045fa50b529fb9f2c4e/joomla/components/com_samllogin/site/views/samllogin/view.html.php#L20-L26

2019-10-04 15:13 UTC, P2-718na commented on joomla/components/com_samllogin/site/controller.php
> +      ->where($db->quoteName('token').' = '.$token)
Risolto:
https://github.com/scuolaonlineservice/sos-users/blob/76346a3c4adb830535f1d045fa50b529fb9f2c4e/joomla/components/com_samllogin/site/views/samllogin/view.html.php#L26-L26

2019-10-04 15:13 UTC, P2-718na commented on joomla/components/com_samllogin/site/views/samllogin/view.html.php
> +    if($id == 0)  {
Risolto:
https://github.com/scuolaonlineservice/sos-users/blob/76346a3c4adb830535f1d045fa50b529fb9f2c4e/joomla/components/com_samllogin/site/views/samllogin/view.html.php#L20-L24

2019-10-04 19:59 UTC, P2-718na commented
@nicofuccella Ho sistemato le ultime requests e ho finito di rebasare il branch. Ora tutti i commit hanno un messaggio sensato.

2020-01-29 09:12 UTC, nicofuccella reviewed
Ben fatto

2020-01-29 09:12 UTC, merged